
[package]
name = "editor"
version = "0.1.0"
edition = "2021"

[dependencies]
fyrox = { git = "https://github.com/FyroxEngine/Fyrox", tag = "v0.33" }
fyroxed_base = { git = "https://github.com/FyroxEngine/Fyrox", tag = "v0.33" }
rust_tetris = { path = "../game" }